### ISSUE TITLE
Next Math.random() after Math.random()=0.7

### ISSUE THREAD

**Issue by IlyaGazman** [TACIXAT/XorShift128Plus#2]
Will it be possible to calculate the next random number of Math.random() after the next Math.rnadom that output 0.7.

Assuming the user got time and he wait for the below code completion, will it be possible to calculate its output?

while(Math.random() != 0.7)
     ;
console.log(Math.random());

**Comment by TACIXAT** [comment]
I think for this you will just recover the state, then run it forward until it is 0.7. That is a very specific value though, might be unlikely to ever hit that (you should threshold when comparing floats / doubles). Sorry for the massive delay on this (:
