### ISSUE TITLE
Global name 'BitVecs' is not defined

### ISSUE THREAD

**Issue by NazarPonochevnyi** [TACIXAT/XorShift128Plus#3]
Hello!

When I run your code I have this error:

`BROWSER: chrome`
`[0.8333085432653353, 0.08162196013326506, 0.4752549301773037]`
`Traceback (most recent call last):`
`  File "main.py", line 186, in <module>`
`    main()`
`  File "main.py", line 152, in main`
`    ostate0, ostate1 = BitVecs('ostate0 ostate1', 64)`
`NameError: global name 'BitVecs' is not defined`

I'm using Python 2.7 and boto-2.49.0 z3-0.2.0 libs.

**Comment by ninjabose** [comment]
Same problem! Any solution? Tried different versions of z3 but it didn't work

**Comment by TACIXAT** [comment]
This should be a z3 installation / import issue. Try to install it with pip. I took out the custom path.

**Comment by luisfontes19** [comment]
Had the same issue, fixed with:
pip install z3-solver
