### ISSUE TITLE
Still fails at Chrome

### ISSUE THREAD

**Issue by gerald-dotcom** [TACIXAT/XorShift128Plus#6]
I know you updated the code but the thing still prints unsat along with some array of numbers.

Find example below, and I did even tried with 10, 15, 600 length inputs but still doesn't work.

Input: 

[ 0.3177472298521653, 0.27438638670402216, 0.9738289241644089, 0.24225661019352596, 0.40700607291649016]

Output: 

BROWSER: chrome
[0.40700607291649016, 0.24225661019352596, 0.9738289241644089, 0.27438638670402216, 0.3177472298521653]
UNSAT

**Comment by TACIXAT** [comment]
Worked fine with these `[0.20926634066056882, 0.75960039311181, 0.005383248688086484, 0.8187067594904363, 0.7500149090603658]`, tested just now. Try it in an empty tab, make sure you have pulled the latest version of this repo.

No need to comment in other issues.

**Comment by gerald-dotcom** [comment]
@TACIXAT 
The values you given are working fine but mine isn't 

I tried with empty tab,

Input: 
dubs = [0.6429813385473633, 0.14884010006851978, 0.897278486341667, 0.24334388228988457, 0.5273349722570018]

Output: 
BROWSER: chrome
[0.5273349722570018, 0.24334388228988457, 0.897278486341667, 0.14884010006851978, 0.6429813385473633]
UNSAT

**Comment by TACIXAT** [comment]
I don't know what to tell you, I don't have enough info. Version of Chrome? Latest of my code? How are you collecting values?

**Comment by gerald-dotcom** [comment]
@TACIXAT 

Version is 81.0.4044.122 (Official Build) (64-bit)

Latest of my code: Yes, it's

How are you collecting values?

By typing Math.random() in Dev Tools Console

**Comment by TACIXAT** [comment]
Try the loop provided in the code to collect values.

**Comment by gerald-dotcom** [comment]
@TACIXAT 

With loop, it works but without loop it doesn't. Do you have any clue why is that?

**Comment by TACIXAT** [comment]
I think it is probably a timing issue with other tabs grabbing random values between when you do. The loop collects them fast enough that that doesn't happen.

**Comment by gerald-dotcom** [comment]
> I think it is probably a timing issue with other tabs grabbing random values between when you do. The loop collects them fast enough that that doesn't happen.

I don't have any other tab, just tried with one tab. it's strange that this happens. 

So we can assume that this is secure to use in server-side (NOT CLIENT SIDE) as one have to be fast enough to grab the inputs (Network latency affect the speed)?

**Comment by gerald-dotcom** [comment]
An attacker would have to achieve nano-second level speed (For loops already do) to get sample values if what you're saying is true.

I think it's possible as High Frequency Traders achieved this kind of speed but it's costly.
